version: '3'

services:
  fabric.realtime:
    image: fabric.realtime
    build:
      context: ./Fabric.Realtime
      dockerfile: Dockerfile
    environment:
      ConnectionString: Server=sql.data;database=FabricRealtime;User=sa;Password=P@ssw0rd;
      MessageBrokerPort: 5672
    depends_on:
      - rabbitmq
      - sql.data

  rabbitmq:
    image: rabbitmq
    ports: 
      - 5672:5672

  sql.data: 
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    ports:
      - 1433:1433